##############################
#        SERVER
##############################
spring.application.name=YouTube
server.port=8080
server.url=http://localhost:${server.port}

##############################
#        DATABASE
##############################
spring.datasource.url=jdbc:postgresql://localhost:8081/youtube_db
spring.datasource.username=youtube_user
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


