##############################
#        SERVER
##############################
spring.application.name=YouTube
server.port=8081
server.url=http://localhost:${server.port}

##############################
#        DATABASE
##############################
spring.datasource.url=jdbc:postgresql://localhost:8081/youtube_db
spring.datasource.username=youtube_user
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##############################
#        EMAIL
##############################
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=sadriddindusanov@mail.ru
spring.mail.password=172vpd0y2oXPtWJWKvXo
spring.mail.protocol=smtps

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000

########################
#        Attach        #
########################
attache.folder=attaches
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

########################
#        JWT
########################
jwt.secret.key=vSgWbN3qZ6v9y+BQE/H+McQfTjWnZr4u7x/AlC+F=JaNdRgUkXp2s5v8y/BtE/H+

