###register
POST localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "name": "Azamat",
  "surname": "O'rmonov",
  "email": "azamaturmanov822@gmail.com",
  "password": "12345"
}

###verify
POST localhost:8080/api/v1/auth/verify
Content-Type: application/json

{
  "email": "azamaturmanov822@gmail.com",
  "code": "934905"
}

###login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "azamaturmanov822@gmail.com",
  "password": "12345"
}