###register
POST localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "name": "Alish",
  "surname": "Alishev",
  "email": "sardornurmatov815@gmail.com",
  "password": "00000"
}

###verify
POST localhost:8080/api/v1/auth/verify
Content-Type: application/json

{
  "email": "sardornurmatov815@gmail.com",
  "code": "849180"
}

###login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "00000"
}

###login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "oqmol24@gmail.com",
  "password": "12345"
}