###change password
PUT localhost:8080/api/v1/profile/update/password
Content-Type: application/json
Authorization: Bearer jwt

{
  "oldPassword": "",
  "newPassword": ""
}

###update password
POST localhost:8080/api/v1/profile/update/email
Content-Type: application/json
Authorization: Bearer jwt

{
  "email": "forexample@gmail.com"
}

###verify and update email
PUT localhost:8080/api/v1/profile/update/email-verify
Content-Type: application/json
Authorization: Bearer jwt

{
  "email": "forexample@gmail.com",
  "code": ""
}

###update detail
PUT localhost:8080/api/v1/profile/update/detail
Content-Type: application/json
Authorization: Bearer jwt

{
  "name": "Test",
  "surname": "Testov"
}

###update photo
PUT localhost:8080/api/v1/profile/update/photo
Content-Type: application/json
Authorization: Bearer jwt

{
  "attachId": "uuid.format"
}

###get profile
GET localhost:8080/api/v1/profile/profile-detail/{id}
Authorization: Bearer jwt

###create
POST localhost:8080/api/v1/profile/create-profile
Content-Type: application/json
Authorization: Bearer jwt

{
  "name": "Admin",
  "surname": "Adminov",
  "email": "forexample@gmail.com",
  "password": "",
  "role": "ROLE_ADMIN"
}

